// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuEBs4C6sx5cSFJhfhIPBvFIB79Ey3DpY',
    appId: '1:610586596535:web:4463bd009f590904f0e932',
    messagingSenderId: '610586596535',
    projectId: 'agronu-56623',
    authDomain: 'agronu-56623.firebaseapp.com',
    storageBucket: 'agronu-56623.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5xaQar3Egt2KTLrIEooV9YqBwilKXYJY',
    appId: '1:610586596535:android:35ed6a055fb63203f0e932',
    messagingSenderId: '610586596535',
    projectId: 'agronu-56623',
    storageBucket: 'agronu-56623.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASUMGrilB4RR7qvTBiY7aNBa0Mg6hlnKc',
    appId: '1:610586596535:ios:1bc15d05a1192f40f0e932',
    messagingSenderId: '610586596535',
    projectId: 'agronu-56623',
    storageBucket: 'agronu-56623.firebasestorage.app',
    iosBundleId: 'com.example.agronu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASUMGrilB4RR7qvTBiY7aNBa0Mg6hlnKc',
    appId: '1:610586596535:ios:1bc15d05a1192f40f0e932',
    messagingSenderId: '610586596535',
    projectId: 'agronu-56623',
    storageBucket: 'agronu-56623.firebasestorage.app',
    iosBundleId: 'com.example.agronu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuEBs4C6sx5cSFJhfhIPBvFIB79Ey3DpY',
    appId: '1:610586596535:web:7de882a5c785304ef0e932',
    messagingSenderId: '610586596535',
    projectId: 'agronu-56623',
    authDomain: 'agronu-56623.firebaseapp.com',
    storageBucket: 'agronu-56623.firebasestorage.app',
  );
}
